/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'avrj' at '11/1/15 6:08 PM' with Gradle 2.7
 *
 * @author avrj, @date 11/1/15 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
